package com.metrics.verifycomposemetricsplugin

import org.gradle.api.GradleException

/**
 * MissingComposeMetricsException
 *
 * Exception that should indicate to the user that they have not generated
 * any compose metric files.
 *
 */
public class MissingComposeMetricsException: GradleException() {
    override val message: String
        get() =  "You are trying to verify compose metrics but the metrics files does not exist " +
                "in your build folder. \n Are you using `./gradlew verifyComposeMetrics` ? \n" +
                "You can make sure that the folder is generated by " +
                "adding `-PgenerateComposeMetrics` flag. \n" +
                "The command is then `./gradlew verifyComposeMetrics -PgenerateComposeMetrics`"
}
