name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey seems like this is your first issue in this repo! Congratz! Thank your for opening an issue here! Please make sure that your have looked through the current isues for duplications before you submit."
        pr-message: "Wow! This is your first PR in this repository! Congratulations and thank you for your contribution!"
